# Generated by Django 4.2.5 on 2023-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeakedCredential',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('source', models.TextField()),
                ('password', models.TextField()),
                ('domain', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunSQL(
            sql="CREATE INDEX myapp_leakedcredential_username_password ON public.myapp_leakedcredential USING btree (username, password);",
            reverse_sql="DROP INDEX public.myapp_leakedcredential_username_password;",
        ),

        migrations.RunSQL(
            sql="CREATE INDEX leaked_credentials_username_gin_idx ON leaked_credentials USING GIN (username gin_trgm_ops);",
            reverse_sql="DROP INDEX leaked_credentials_username_gin_idx;",
        ),
    ]
