# Generated by Django 4.2.6 on 2023-10-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfile',
            name='breach_site',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailfile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
