# Generated by Django 4.2.5 on 2023-10-16 05:55

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfile',
            name='encrypted_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, null=True)),
        ),
    ]
