# Generated by Django 4.2.6 on 2023-10-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0002_emailfile_encrypted_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfile',
            name='encrypted_name',
        ),
        migrations.AddField(
            model_name='emailfile',
            name='password',
            field=models.CharField(default='temp_password', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailfile',
            name='source',
            field=models.CharField(default='temp_source', max_length=255),
            preserve_default=False,
        ),
    ]
