# Generated by Django 4.2.6 on 2023-10-27 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0003_alter_emailfile_breach_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailfile',
            old_name='breach_site',
            new_name='source',
        ),
    ]
