# Generated by Django 4.2.6 on 2023-10-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0003_remove_emailfile_encrypted_name_emailfile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfile',
            name='password',
        ),
        migrations.AddField(
            model_name='emailfile',
            name='_encrypted_password',
            field=models.CharField(default='default_encrypted_password', max_length=255),
        ),
    ]
