# Generated by Django 4.2.6 on 2023-10-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0004_remove_emailfile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfile',
            name='_encrypted_password',
        ),
        migrations.AddField(
            model_name='emailfile',
            name='password',
            field=models.CharField(default='temp_password', max_length=255),
        ),
    ]
