# Generated by Django 4.2.5 on 2023-11-08 22:34

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('np_app', '0005_registereduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfile',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True)),
        ),
    ]
